# Generated by Django 5.0.1 on 2024-02-17 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('manager', 'Manager'), ('head', 'Head'), ('leader', 'Leader'), ('staff', 'Staff')], max_length=50)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('hired_date', models.DateField()),
                ('salary', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='employees.departments')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='employees.positions')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='head',
            field=models.ManyToManyField(blank=True, related_name='head', to='employees.employees'),
        ),
    ]
