# Generated by Django 5.0.1 on 2024-02-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.positions'),
        ),
    ]
