# Generated by Django 5.0.1 on 2024-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employees_employment_type_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
