# Generated by Django 5.0.1 on 2024-02-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employee_id',
            new_name='employee_number',
        ),
    ]
